### ISSUE TITLE
Comparison with Yasnippet

### ISSUE THREAD

**Issue by karthink** [ymarco/auto-activating-snippets#1]
The Yasnippet description reads

> This package was made in response to yasnippet’s inability to auto-expand.

Is this true? I've been using Yasnippet with the `condition: auto` clause to auto-expand snippets for an year now.

Is there any reason besides auto-expansion to prefer this package to Yasnippet?

**Comment by ymarco** [comment]
You're referring to https://github.com/joaotavora/yasnippet/issues/998#issuecomment-494438399, right? Honestly although I've seen that solution in the past I've forgotten about it completely when writing this engine.

One reason to prefer this package might be performance; the tracking mechanism is very simple and shouldn't be really affected by having tons and tons of snippets loaded, no more than `lookup-key` is affected by being called on a large keymap. In the yasnippet approach every snippet condition would be called after each keypress to check if it evaluates to `'auto`. 

Anyway, I'll correct the readme with a link to that issue. If yasnippet is working fine for you, no need to switch :).

**Comment by karthink** [comment]
Thank you for the clarification. Although setting up Yas for auto-expansion involves adding to `post-command-hook`, I haven't noticed any slowdown with ~100 snippets loaded for the major mode. I'll consider switching to this if it becomes a problem
