### ISSUE TITLE
Activate Everywhere

### ISSUE THREAD

**Issue by vale981** [ymarco/auto-activating-snippets#12]
Is it possible to define snippets that work everywhere and even in the minibuffer?

**Comment by ymarco** [comment]
This seems to work in the minibuffer.


(aas-set-snippets 'global
                  "test" "TEST")
(define-globalized-minor-mode aas-global-mode aas-mode
  (lambda ()
    (aas-activate-keymap 'global)
    (aas-mode +1)))
(aas-global-mode +1)


Sorry for the late response, I thought something special would be needed
for minibuffers, but it doesn't seem so.

**Comment by vale981** [comment]
thank you. i had set it up as a hook, but this seems better :]
