### ISSUE TITLE
Activate globally

### ISSUE THREAD

**Issue by legendre6891** [ymarco/auto-activating-snippets#13]
Hi - thanks for this fantastic package! 

Is there a way to make AAS be active globally, or more precisely, in every mode where entering text makes sense? I thought about using `prog-mode-map`, but that doesn't cover e.g. fundamental mode, org-mode, etc. 

Cheers

**Comment by ymarco** [comment]
See #12. Maybe I should just merge my code there into master.

**Comment by legendre6891** [comment]
Thanks — I’d welcome the addition :-)

**Comment by ymarco** [comment]
Preparing to add it, do you by chance have any good examples to showcase this use case in the readme? I can't think of anything

**Comment by legendre6891** [comment]
Thanks @ymarco. The prevailing usecase I have is to turn something like `;--` into —, `;->` into an arrow Unicode character.

the leading semicolon is used as a pseudo namespacing mechanism. I like to use this in all modes, either org mode, text mode, or while programming (inside code comments).
