### ISSUE TITLE
modify `texmathp-tex-commands`

### ISSUE THREAD

**Issue by deshearth** [ymarco/auto-activating-snippets#14]
Is there a way to remove "$" delimiter from function `texmathp`. The auctex document says `texmathp-tex-commands` is customizable. But it seems even after customizing this variable,
it is still detected as math environment when in the dollar sign. I can successfully add new
 commands or environment by modifying that variable but I just can't remove the existing ones from it.

**Comment by ymarco** [comment]
Go read texmathp.el. Something it in has to be responsible for defaults like $.
After a glimpse of it grepping for texmathp-tex-commands, maybe you could remove "$" from texmathp-tex-commands-default and call texmathp-compile. I didn't check though.

**Comment by deshearth** [comment]
Thank you! I’ll try that. I just start using emacs two weeks ago and can’t read elisp very well. Maybe I’ll try reading that later.

**Comment by ymarco** [comment]
Closing due to staleness, feel free to still follow up here
