### ISSUE TITLE
Function to remove snippets?

### ISSUE THREAD

**Issue by jrpat** [ymarco/auto-activating-snippets#15]
It would be handy to have a function like `(aas-rem-snippets 'my-mode "foo" "bar" ...)` to remove individual snippets (and maybe `(aas-rem-snippets 'my-mode)` to clear them all?)

I tried clearing them all by doing `(remhash 'my-mode aas-keymaps)`, but the snippets still got activated when I typed their trigger.

Thanks for the fantastic package, btw! 🎉

**Comment by ymarco** [comment]
Snippets are stored in keymaps. Like keymaps, you remove bindings by
binding to nil.

> It would be handy to have a function like (aas-rem-snippets 'my-mode "foo" "bar" ...).

The readme has an example:

  (aas-set-snippets 'latex-mode
    "supp" nil)

> I tried (remhash 'my-mode aas-keymaps), but the snippets still got activated when I typed their trigger.

That *should* do something, but wouldn't if aas-mode is already active (aas-set-snippets wouldn't too).
You'd need to regenerate aas--prefix-map for it to take effect, by either calling (aas-deactivate-keymap nil) or reapplying a previous (aas-activate-keymap) call.
I suggest to just do it before any keymaps are activated.

**Comment by jrpat** [comment]
Ah ok thanks. I'm moving from vim and missing some knowledge about standard emacs ways of doing things.

Fortunately, I'm finding that `aas-set-snippets` works fine when aas-mode is already active - including removing snippets, so I'll close this issue.
