### ISSUE TITLE
Condition syntax

### ISSUE THREAD

**Issue by jfab20** [ymarco/auto-activating-snippets#16]
I'm kind of new to elisp and I can't figure out how to change the condition in the ```:cond``` block.  I want latex snippets 
that : 
1. Expand only when my cursor is NOT in a math region. However the syntax ```:cond #'(not texmathp)``` doesn't seem to work
2. Have multiple conditions. For example I want a snippet to only expand at the beginning of the line and when my cursor is not inside a texmathp zone, so I would like to add the condition ```(and (looking-back "^beg" nil) (texmathp))``` to my snippet. 

How can I achieve this?

**Comment by slotThe** [comment]
@jfab-123 the `:cond` keyword takes a function, so for your first example it would be `:cond #'(lambda () (not (texmathp)))`.  The second one is then similar:#15 

``` emacs-lisp
:cond #'(lambda () (and (looking-back "^beg" nil)
                        (not (texmathp))))
```

**Comment by ymarco** [comment]
The argument for :cond should be a function object. #'(not ...) doesn't create a new function: you need a lambda for that.

https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#A-Simple-Lambda-Expression-Example

An example for a lambda that negates texmathp:

  (aas-set-snippets 'some-mode
    :cond (lambda ()
            (not (texmathp)))
    "aaa" "b")

This is more of a question about elisp, but the function docs in aas is lacking as well, so I don't blame you. I need to work on that.

**Comment by jfab20** [comment]
Thanks!
