### ISSUE TITLE
Snippets binded to functions 

### ISSUE THREAD

**Issue by mits-haruko** [ymarco/auto-activating-snippets#17]
Using the minimal configuration on the README as an example, I have the `\frac` snippet to be as

`"//" (lambda () (interactive)`
           `(yas-expand-snippet "\\frac{$1}{$2}$0"))`

inside of `aas-set-snippets`. However, the snippet doesn't seem to understand that the inner brace `}` after `$1` and before the second `{` is supposed to enter as part of the snippet, which results in getting a second one in between, so I end up with something like this:

`\frac{ } } { }`

As a further issue, the navigation between the snippet entries also doesn't work.

Is there some further configuration to be done so I can call `yas-expand-snippet`?

**Comment by ymarco** [comment]
This is an issue with smartparens, which tries to close inserted opening braces and messes up.
Check the definitions of snippets in laas
https://github.com/tecosaur/LaTeX-auto-activating-snippets/
we work around it there. (see laas--shut-up-smartparens)

**Comment by mits-haruko** [comment]
I didn't expect that passing `(aas--shut-up-smartparens)` would do it. Thank you.
