### ISSUE TITLE
 character input

### ISSUE THREAD

**Issue by FrancisH-C** [ymarco/auto-activating-snippets#2]
Is there a way to include special code sequences as aas-snippets ?Something like this:
```
  (aas-set-snippets 'text-mode
                    ;; expand unconditionally
                    "al <TAB> " "\alpha"
                    "i \C-n" "ī")
```
I'm sorry if it sounds stupid, it seems really easy but I don't know where to get that info. It may just be me wanting a weird functionnality.
I know there are ways to do this with yasnippets, but I really like the auto-activating and reggex completion part of this packages.

Thank you!

**Comment by ymarco** [comment]
No there is not. The engine runs exclusively on `post-self-insert-hook`, and most of the time `TAB` and `C-n` are bound to a function that would not trigger the hook. If it `TAB` was unbound, maybe it would work? `C-n` would definitely not though, Emacs would just complain about `C-n is undefined`.

May I suggest instead to bind functions directly to these keys? Something like 
```emacs-lisp
(global-set-key "\t" (lambda () (interactive)
                       (unless (aas-expand-snippet-maybe "al " "\\alpha " nil)
                         (funcall-interactively #'your-normal-TAB-function))))
```
Its less elegant and but should work with `C-n` as well. `aas-expand-snippet-maybe` first checks that the key (`"al "` in our example) is fully typed and only then expands so there shouldn't be any complications.

**Comment by FrancisH-C** [comment]
The nil in `(aas-expand-snippet-maybe "al " "\\alpha " nil)` should not be a condition function looking at last two characters? 
Because if I replace `your-normal-TAB-function` with a simple string insert, "al\t" (`al TAB`) never gets expanded.

**Comment by ymarco** [comment]
> The nil in (aas-expand-snippet-maybe "al " "\\alpha " nil) should not be a condition function looking at last two characters?

No, `aas-expand-snippet-maybe` does that first not depending on the condition. You can read the code.
>  Because if I replace your-normal-TAB-function with a simple string insert, "al\t" (al TAB) never gets expanded.

It works for me. I tested it before posting and tested again now. Note though that the key is `"al "`, with a space at the end. I thought you meant there to be a space in your original question.

**Comment by FrancisH-C** [comment]
I'm sorry, I definitely had not seen the space plus my elisp is really bad. 

Anyway, it works perfectly. It's really the functionality I wanted, thank you very much for your time and your package.
