### ISSUE TITLE
Expand yas-snippet by name

### ISSUE THREAD

**Issue by mychris** [ymarco/auto-activating-snippets#21]
I did not find a good way to expand yas-snippet by its name. Is this already possible?

```elisp
(aas-set-snippets 'c-mode
  "if" '(yas "if"))
```

just expands to if, since the YASnippet shorthand form expects a full snippet, not just a name. I was able to expand a snippet using something along the line of (don't recall the exact syntax right now)

```elisp
(aas-set-snippets 'c-mode
  "if" `(yas ,(yas-lookup-snippet "if")))
```

but the problem is that the lookup of the snippet is done during configuration time, so if the snippet expands it always uses the same snippet, even if one changed it during runtime.
I ended up using:

```elisp
(aas-set-snippets 'c-mode
  "if " #'(lambda () (interactive) (yas-expand-snippet (yas-lookup-snippet "if"))))
```

but this is very cumbersome to use. Of course, I could write my own macro for it, but I thought this might be a useful feature for others as well, or I have overlooked something and there is a solution to my problem.

Is it already possible to expand a yas-snippet using its name, or, if not, would you accept a patch to add something like a yas-by-name lookup method like:

```elisp
(aas-set-snippets 'c-mode
  "if" '(yas-by-name "if"))
```

**Comment by ymarco** [comment]
Why not write an interactive function that looks at  `aas-transient-snippet-key` variables and looks up the yas snippet based on that? That would be easy enough if the aas key and yas snippet name are the same.

**Comment by mychris** [comment]
Yes, but the names are not always the same.

Like I said, it is not really a problem to do this without an extension to the package, since a function can be provided. But when I discovered your package and read that it works together with yasnippets, I thought that this feature would be there, but couldn't find it.

So this was mostly a question. Maybe an example in the documentation would also be enough, so people are aware that this is not built in and have something to start with.

**Comment by ymarco** [comment]
I'd like to keep these shorthand yas/tempel snippet forms minimal and not add more. aas didn't even have them three months ago [[1]](https://github.com/ymarco/auto-activating-snippets/commit/d534f0062375f6a82f6eb4a6cc2a1d3d3a4fdc34). The canonical way to do this *should* be to bind to functions, imo.

And it's not that bad; with macros you can shorten it down to
```emacs-lisp
(aas-set-snippets 'c-mode
  "if" (cmd! (my/yas-expand-snippet-by-name "if")))
```

**Comment by mychris** [comment]
No problem. Like I said, maybe a hint in the readme would be good. I will close this issue then.
Thanks.
