### ISSUE TITLE
how to reuse existing yasnippet/tempel snippets

### ISSUE THREAD

**Issue by emacsbliss** [ymarco/auto-activating-snippets#22]
Let's say I have a snippet defined in yasnippet called `src`, how can I use it with `aas`?

this example from readme I think it's not doing what I want since we actually define the snippet here?

```
"amin" '(yas "\\argmin_{$1}") ; 
```

would like to know what's the right way to use my existing snippets, thanks!!

**Comment by ymarco** [comment]
Take a look at #21
