### ISSUE TITLE
aas--modes-to-activate will return the wrong sequence for aliases

### ISSUE THREAD

**Issue by sirikid** [ymarco/auto-activating-snippets#7]
JFYI, `aas--modes-to-activate` will break on aliases (e.g. `javascript-mode`).

https://github.com/ymarco/auto-activating-snippets/blob/dd58b7601ec536980a14540bddac53f5d1c1da08/aas.el#L229-L236

I use the following function, but it returns only "real" functions, if you allow aliases you should tweak it a bit.
```elisp
(defun sp--mode-list (mode)
  (let (result)
    (while mode
      (let ((fn (symbol-function mode)))
        ;; if MODE's function is a symbol then mode is an alias
        (while (and fn (symbolp fn))
          (setq mode fn
                fn (symbol-function mode))))
      (push mode result)
      (setq mode (get mode 'derived-mode-parent)))
    result))
```

**Comment by ymarco** [comment]
Thank you! 
> if you allow aliases you should tweak it a bit

Yeah, done that.

**Comment by sirikid** [comment]
Just remembered, there is also [parent-mode](https://github.com/Fanael/parent-mode), but I don't like its design.

**Comment by ymarco** [comment]
Eh, seems to do the same thing as my loop with more steps.
I think we're good now.
